### ISSUE TITLE
flutter run -v 抛错

### ISSUE THREAD

**Issue by Seek-knowledge** [LittleMango/flutter_widget_sample#1]
========================我机器版本是：
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (13 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
========================错误内容如下：
[  +92 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +3 ms] executing: idevice_id -h
[ +140 ms] /usr/bin/xcrun simctl list --json devices
[ +573 ms] Your application could not be compiled, because its dependencies could not be established.
                   The following Dart file:
                     /Volumes/D/code/Flutter/ios_apps/flutter_widget_sample/lib/lib.dart
                   ...refers, in an import, to the following library:
                     /Volumes/D/code/Flutter/ios_apps/flutter_widget_sample/lib/b/baselineSample.dart
                   Unfortunately, that library does not appear to exist on your file system.
[  +10 ms] "flutter run" took 912ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:417:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by LittleMango** [comment]
从栈来看说的是找不到/Volumes/D/code/Flutter/ios_apps/flutter_widget_sample/lib/lib.dart这个文件。你可以先确认一下该文件是否存在(我感觉是存在的)。

**我的 Flutter 套件版本和你的一致，我将项目 clone 在两台mac 上都可以编译安装。**

下面是我的操作步骤

1. 执行 flutter upgrade 命令，将 Flutter 升级到最新版本。
2. 执行 flutter doctor 命令，确保本机 Flutter 套件是正常的。
3. 更新项目中的 packages
* Android Studio -> Tools -> Flutter -> Flutter Packages Get
* Android Studio -> Tools -> Flutter -> Flutter Packages Upgrade

你可以按照以上步骤检查、更新项目依赖包试一下。

**Comment by Seek-knowledge** [comment]
请问有没有遇到过：
Running "flutter packages upgrade" in ios_app2...                
Because every version of flutter_test from sdk depends on csslib 0.14.5 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because ios_app2 depends on flutter_test any from sdk, version solving failed.


我现在不管是更新还是拉包，都是这个报错。
换了git上的新版也是这样~~

**Comment by LittleMango** [comment]
因为有一座长城墙了你[偷笑]

具体看这个[Flutter #20809 (comment)](https://github.com/flutter/flutter/issues/20809#issuecomment-415273351)

**Comment by LittleMango** [comment]
上面的代理在电信的网络是能起到作用的。

如果移除代理的话，那么可能需要自己重新挂个终端代理。

**Comment by Seek-knowledge** [comment]
其实我在bash_profile中是有设置的====如下====
#flutter
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

export flutter=/Volumes/D/Software/Flutter-tools/OSX/flutter
export ANDROID_HOME=/Users/mac/Library/Android/sdk

export PATH=${PUB_HOSTED_URL}:${FLUTTER_STORAGE_BASE_URL}:${flutter}/bin:${PATH}
++++++++++++++++
表示很好奇原先的PUB_HOSTED_URL和FLUTTER_STORAGE_BASE_URL是指向哪个地址

**Comment by LittleMango** [comment]
1.  指向哪里？你把代理地址删了，更新的时候看看终端连接到哪里...
2. [移动网络有问题，电信网络没问题](https://github.com/flutter/flutter/issues/20809#issuecomment-415045069)，你使用的是电信网络吗？

**Comment by LittleMango** [comment]
有一个方法肯定有效，那就是删除下面的镜像代理

```
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
然后自己翻墙更新。

**Comment by Seek-knowledge** [comment]
删掉镜像代理后shadowsocks开全局，然后就卡在拉包这块。泪目，这玩意儿真难折腾。

**Comment by LittleMango** [comment]
终端输入 
```
curl -I https://google.com
```
能否输出

```
HTTP/1.1 200 Connection established

....
HTTP/1.1 .....
```
我之前用长城宽带的时候虽然挂了 VPN，但是就是翻不过去。

**Comment by Seek-knowledge** [comment]
我黑苹果上的CURL版本是7.54的
测试后结果是：
macs-iMac:~ mac$ curl -I https://google.com
curl: (7) Failed to connect to google.com port 443: Operation timed out
--但浏览器谷歌的访问时正常的。

  我发现我new一个新的flutter然后添加新包banner（PS：pub上的）。
  然后flutter packages get执行，发现new出来的项目拉包跑起来了；
但想跑你这个项目的时候就...
----------Running "flutter packages get" in flutter_widget_sample-master...      
Because every version of flutter_test from sdk depends on csslib 0.14.5 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because flutter_ui_demo depends on flutter_test any from sdk, version solving failed.----------
 
pub get failed (1)

**Comment by LittleMango** [comment]
这样说的话，你的shadowsocks只是代理了80端口的，所以**终端的数据没有走代理。**

那就来一个规避的方法吧，打开`pubspec.yaml`，
注释掉 flutter_test。
```
dev_dependencies:
#  flutter_test:   #注释掉这两行
#    sdk: flutter   #注释掉这两行
```

然后等你有电信网的时候就可以使用之前设置的代理，把 csslib 更新到最新版本。

**Comment by Seek-knowledge** [comment]
shadowsocks没仔细研究过，不过配置显示socks5代理1080,http代理了1081端口。
==========发现错误了===============
[ +542 ms] Your application could not be compiled, because its dependencies could not be established.
                   The following Dart file:
                     /Volumes/D/code/Flutter/ios_apps/flutter_widget_sample/lib/lib.dart
                   ...refers, in an import, to the following library:
                     /Volumes/D/code/Flutter/ios_apps/flutter_widget_sample/lib/b/baselineSample.dart
                   Unfortunately, that library does not appear to exist on your file system.
[  +10 ms] "flutter run" took 863ms.
-----------------------
然后我发现lib.dart文件中引用报错baselineSample.dart，正确文件名是baseLineSample.dart.
修改完就可以跑了。

**Comment by LittleMango** [comment]
还真是的，我非常好奇，我的两台电脑都没报错[汗]。

我稍后更新一下，将文件名修改成小写的baselineSample.dart，毕竟 baseline 这个 widget 的 'l' 是小写的

**Comment by Seek-knowledge** [comment]
我也是瞎搞发现了，我是直接git下来，或许你没成功提交之类的。
总之，谢谢你的demo，也是我找到为数不多能跑的demo，好多都是报要SDK2.0.0以下的，我觉得应该是dart的版本，但是我不知道应该怎么弄2.0以下的dart sdk，
这也是我觉得flutter难学的一个点。

**Comment by LittleMango** [comment]
好了，我更新了 baseLineSample.dart -> baselineSample.dart。
还有将所有用例说明改成了 Markdown 格式，增加可读性，你可以 update一下试试。
